### ISSUE TITLE
Buggy record selection

### ISSUE THREAD

**Issue by schackartk** [MahdiKarimian/DIF#7]
Flake8 has pointed out the `record` is being referenced, but it may never have been created. For instance, if an empty file is created

```
touch empty.fa
```

When this empty file is passed as an input file, then the line `for record in SeqIO.parse(args.file, "fasta"):` doesn't instantiate the `record` variable. Because of this, a runtime error occurs:

```
$ ./dif.py -o foo.png empty.fa
Traceback (most recent call last):
  File "/home/ken/documents/DIF/./dif.py", line 269, in <module>
    main()
  File "/home/ken/documents/DIF/./dif.py", line 110, in main
    len(record.seq)
UnboundLocalError: local variable 'record' referenced before assignment
```

Additionally, the behavior is unexpected when a non-existent `--recordid` is supplied:
```
./dif.py -o foo.png --recordid not_a_real_record sequence.fasta 
Select this record NC_003076.8:c5411766-5406863 
x min max y min max 0 , 1000 , 0 , 1000
end of Generating image
```

This should raise an exception, and not just select the last record in the file.

**Comment by MahdiKarimian** [comment]
What is your recommendation for such an error?

**Comment by MahdiKarimian** [comment]
The commit solves this issue.
